export const shopCategories = [
  { value: "electronics", label: "Electronics & Gadgets" },
  { value: "fashion-men", label: "Men's Fashion" },
  { value: "fashion-women", label: "Women's Fashion" },
  { value: "fashion-kids", label: "Kids & Baby Fashion" },
  { value: "home-living", label: "Home & Living" },
  { value: "kitchen-appliances", label: "Kitchen Appliances" },
  { value: "beauty-personal-care", label: "Beauty & Personal Care" },
  { value: "health-wellness", label: "Health & Wellness" },
  { value: "sports-outdoors", label: "Sports & Outdoors" },
  { value: "automotive-parts", label: "Automotive & Parts" },
  { value: "books-media", label: "Books, Music & Movies" },
  { value: "toys-hobbies", label: "Toys & Hobbies" },
  { value: "pet-supplies", label: "Pet Supplies" },
  { value: "office-stationery", label: "Office & Stationery" },
  { value: "jewelry-watches", label: "Jewelry & Watches" },
  { value: "groceries-food", label: "Groceries & Gourmet Food" },
  { value: "furniture", label: "Furniture" },
  { value: "tools-hardware", label: "Tools & Hardware" },
  { value: "garden-outdoor", label: "Garden & Outdoor" },
  { value: "smart-home", label: "Smart Home Devices" },
  { value: "computers-laptops", label: "Computers & Laptops" },
  { value: "mobile-accessories", label: "Mobile Accessories" },
  { value: "gaming-consoles", label: "Gaming & Consoles" },
  { value: "industrial-scientific", label: "Industrial & Scientific" },
  { value: "art-crafts", label: "Art, Crafts & Sewing" },
  { value: "musical-instruments", label: "Musical Instruments" },
  { value: "luggage-travel", label: "Luggage & Travel Gear" },
];
